### ISSUE TITLE
Write tests for the partner access service

### ISSUE THREAD

**Issue by eleanorreem** [chaynHQ/bloom-backend#227]
**Background**
We want to have a more robust code base. When bloom was developed it was not thoroughly tested and we are trying to fill in the gaps. 

**Task**
- write tests for /src/partner-access/partner-access.service.spec.ts. 
- the file has already been created and a couple of tests have been started in src/partner-access/partner-access.service.spec.ts
- if you see logic in the code that doesn't make sense or can be improved, let @swetha-charles or @eleanorreem know as it is possible that the logic is wrong and create a bug report. 

**Possible test scenarios**
- a partnerAdmin fails to create a partner access code as the partner doesn't exist
- a user cannot assign an access code to their account as the user doesn't exist
- a user cannot assign an access code to their account as the partner doesn't exist
- a user successfully assigns partner access codes on sign up
- a user fails to assign partner access code on sign up

**Comment by kyleecodes** [comment]
Testing comments bot.

**Comment by haydnba** [comment]
I would be interested in twirling on this

**Comment by kyleecodes** [comment]
@haydnba you are assigned!

**Comment by kyleecodes** [comment]
Hi @haydnba thank you for your contributions to Chayn!
I know you have been busy with other contributions, but are you still working on this one? No worries if you need more time. Please let us know if you need anything need any help. Otherwise I will unassign this to open it back up to new contributors. Thanks again!

**Comment by haydnba** [comment]
Hi @kyleecodes 👋🏼

Sorry I dropped the ball on this one! Yeah I've had a load of other stuff on recently so not been able to look at this - I was actually intending to speak to someone on the team regarding how accurate this ticket is as I saw that there are now quite a number of tests implemented on the files mentioned. 

In any case I think for now maybe it's best to unassign me and I'll see if I can get back to it soon

**Comment by eleanorreem** [comment]
Hey @haydnba, thanks for your input 😄  This ticket was created more than 18 months ago so I think we should probably close it. @kyleecodes be good to have a process for reviewing tickets that are older than 6 months.
