### ISSUE TITLE
Update backend continuous intergration to match bloom-frontend

### ISSUE THREAD

**Issue by eleanorreem** [chaynHQ/bloom-backend#229]
**Background**
We recently updated the bloom-frontend integration flow in github actions. It has worked really well for us and we want the same steps to happen in the backend. 

**Task**
- have a look at the integration steps in bloom-frontend .github/workflows file (ignore the manual-deploy workflows as they are not currently working)
- the workflows might not exactly match but get them as close as you can (e.g. there is no cypress in the backend etc)
- Please ask any questions to @swetha-charles  or @eleanorreem  if you have any issues

**Comment by annarhughes** [comment]
Added in #368
