### ISSUE TITLE
Add Active column to Partner Admin Column

### ISSUE THREAD

**Issue by eleanorreem** [chaynHQ/bloom-backend#311]
### Overview
We want to toggle the permissions of a Partner Admins but maintain the history of a user. For now we want to do this by adding a column "active" with a boolean type to the partner admin table. The column is required (i.e. cant be null) and the default is set to true. 

### Action Items

- [ ] Create a branch
- [ ] Update the entity in /bloom-backend/src/entities/partner-admin.entity.ts
- [ ] Run the migration script `yarn migration:generate`
- [ ] Check that the migration makes sense
- [ ] Run the migration script `yarn migration:run` 
- [ ] Check you see what is expected in your database
- [ ] Run tests
- [ ] Commit and make PR
- [ ] Tag @eleanorreem and @kyleecodes in the PR

### Resources
- see [Typeorm documentation](https://github.com/typeorm/typeorm) for help with writing migration

**Comment by jobayer12** [comment]
@eleanorreem Review the pull request #338.

**Comment by kyleecodes** [comment]
Thank you for your PR @jobayer12!

We are working on reviewing your PR very soon. Meanwhile wanted to let you know for future reference that as per our [Contributing Guidelines](https://github.com/chaynHQ/bloom-backend/blob/develop/CONTRIBUTING.md) we do require that contributors **ask to be assigned on issues before opening a PR**, this helps us track contributor progress. I've assigned you to this issue so no worries, but for next time it's something to keep in mind. :)

Happy Hacking!
