### ISSUE TITLE
Bump @nestjs/core from 8.0.11 to 9.0.5

### ISSUE THREAD

**Issue by eleanorreem** [chaynHQ/bloom-backend#321]
Overview
Dependabot [PRs](https://github.com/chaynHQ/bloom-backend/pull/275) are automatically created. Our cypress tests don't currently run against code on the branch so we need to run them manually for now. An automated way of doing this is in the pipeline. However, for now we need to run the tests manually

Action Items
- [x] Clone the branch raised by dependabot to your local computer
- [x]  Run up both bloom-backend and bloom-frontend to ensure that this change in dependency has not affected the site
- [x]  Run backend unit tests to ensure they're all passing
- [ ]  Run frontend cypress tests to ensure they're all passing
- [x]  Commit any changes to the dependabot branch and push up
- [ ]  Comment on the ticket that this change has been verified and request reviews from the team (@kyleecodes)

**Comment by strawHat121** [comment]
Hey so I was trying to do this but for this I need to setup and run the repository locally.

Can anyone help me with the .env file content so that I can setup and run the repo locally ?

Thanks

**Comment by kyleecodes** [comment]
Thank you for interest @strawHat121! Happy to help.

I just updated the directions for the `.env` file in the `README.md` to include which variables are required vs. optional, hope that helps!

I can assign you the issue and you may tag me here with any questions, we are online daily during Hacktober.

**Comment by strawHat121** [comment]
Hi @kyleecodes 

Sorry to ping you here again. I was able to get all the env variables of firebase but I am having trouble finding the simplybook variables.

Can you point me towards any documentation or something that can help me in setting it up ?

**Comment by kyleecodes** [comment]
Hey @strawHat121 no worries for tagging me again, happy to help and appreciate your feedback!

I have updated the README again. Since Simplybook variables are only required for testing, you can use dummy values as long as they are in the correct format. You may copy paste the Simplybook values as they are in the README now, they go as follows:

```
SIMPLYBOOK_CREDENTIALS='{"login":"testlogin","password":"testpassword","company":"testcompany"}'
SIMPLYBOOK_COMPANY_NAME=testcompany
```

Thanks for your patience, hope this helps!
