### ISSUE TITLE
Add link to CONTRIBUTING.md file in README.md

### ISSUE THREAD

**Issue by kyleecodes** [chaynHQ/bloom-backend#324]
### Overview
We need to link to the CONTRIBUTING.md file in the README.md so contributors can more easily see the contributing guidelines.

### Action Items
- [ ] Under the title in Bloom Backend section in the `README.md`, above "Technologies Used", add the following:
"To make a contribution, please read our Contributing Guidelines in CONTRIBUTING.md"
- [ ] Make sure the sentence above contains a Markdown link to the repo's CONTRIBUTING.md file. 

### Resources/Instructions
- [How to Create Markdown Links](https://www.markdownguide.org/basic-syntax/#links)

**Comment by maryamkhan14** [comment]
Hi! May I pick this up?

**Comment by kyleecodes** [comment]
Thanks for your interest @maryamkhan14! I see you commented on 2 no-code, good first issues, we limit 1 no-code, good first issue per contributor! Let us know which one you'd prefer an I'll get you assigned ASAP. :)

**Comment by kyleecodes** [comment]
Hey @FardeenCODEIIEST, thank you for asking! Yes I have assigned the issue to you.
