### ISSUE TITLE
Move README.md documentation to new /docs directory

### ISSUE THREAD

**Issue by kyleecodes** [chaynHQ/bloom-backend#325]
### Overview
We should simplify our README by separating the key concepts and architecture guides into their own separate /docs directory, similar to [how Soulmedicine is organized](https://github.com/chaynHQ/soulmedicine/tree/main/docs), and turn the README into a brief overview of the project and quick start guide. 

### Action Items
- [ ] Create a `/docs` folder in the root directory.
- [ ] Move the Key Concepts section of the `README.md` into the `/docs` folder in a file called `key-concepts.md`
- [ ] Move the Database Models section of the `README.md` into the `/docs` folder in a file called `data-architecture.md`
- [ ] Write the following sentence under the "Local Development" section title in the `README.md`:
"For a more detailed explanation of this project's key concepts and architecture, please visit the /docs directory."
- [ ] Make sure the above sentence contains a Markdown link to the `/docs` directory, which would be: https://github.com/chaynHQ/bloom-backend/tree/develop/docs (This is where a README.md file will be located in the near future.)

Resources:
- [How to make Markdown Links](https://www.markdownguide.org/basic-syntax/#links)

**Comment by maryamkhan14** [comment]
Hi! May I pick this up?

**Comment by kyleecodes** [comment]
Thanks for your interest @maryamkhan14! I see you commented on 2 no-code, good first issues, we limit 1 no-code, good first issue per contributor! Let us know which one you'd prefer an I'll get you assigned ASAP. :)

**Comment by ATREAY** [comment]
hey @kyleecodes, can I work on this issue?

**Comment by kyleecodes** [comment]
@ATREAY thanks for your interest, I have assigned you the issue. :)

**Comment by ATREAY** [comment]
Hey @kyleecodes,
I'm running into an error. Should I downgrade my Node version to fix it, or do I need to update the one in the repo? Here's a screenshot for reference.
![error image](https://github.com/chaynHQ/bloom-backend/assets/66585295/a640057c-24a3-449d-97df-22a89a768d72)

**Comment by kyleecodes** [comment]
Great question @ATREAY

I suggest using a node version manager, such as [nvm](https://github.com/nvm-sh/nvm), which can install multiple versions of node on your computer and switch between versions for a given project. For instance, I generally use the latest version of node on my computer, but when I need to run an older node version for a project, I target that specific node version using nvm. It's a simple system once you get it set up.

**Comment by ATREAY** [comment]
Hey @kyleecodes,

I've run into another issue, and I'm hoping you could lend me a hand with it. Here's a screenshot for reference:
![error image](https://github.com/chaynHQ/bloom-backend/assets/66585295/69f2f9e1-0a99-450f-8010-470d94c284b6)

My apologies for reaching out on the weekend.

**Comment by kyleecodes** [comment]
This is an error thrown by the NestJS testing framework, but because this issue is a no-code issue, it is not required for these tests to pass on your computer. The test is failing because you do not have the required environment variables set up, in this case the tokens from Simplybook. For this issue, I would not worry about this.

**Comment by ATREAY** [comment]
Hey @kyleecodes, I've made the necessary updates. Could you please review them when you have some time?

**Comment by ATREAY** [comment]
Hey @kyleecodes, I've created a new pull request that includes only the necessary files. I closed the previous one. Could you please take a look when you have a moment?

**Comment by kyleecodes** [comment]
Perfect thank you @ATREAY!
