### ISSUE TITLE
Link to our Volunteer Info page in our README.md

### ISSUE THREAD

**Issue by kyleecodes** [chaynHQ/bloom-backend#329]
### Overview
Currently, our README links interested volunteers directly to the volunteer form, not to our volunteer info page (which contains the form).  We need the README to link to the [Getting Involved volunteer info page](https://www.notion.so/chayn/Get-involved-423c067536f3426a88005de68f0cab19?pvs=4) instead, similar to how our CONTRIBUTING.md file does.

### Action Items
- [ ] Replace the text in the `README.md` under the Getting Involved section:
If you would like to help Bloom and receive special access to our organization and volunteer opportunities, please get in touch with us to express your interest in volunteering via [this form](https://forms.gle/qXfDdPgJxYwvMmVP7)." 
with the following text:
"If you would like to help Chayn and receive special access to our organization and volunteer opportunities, please visit our Getting Involved page."
- [ ] Make sure the above sentence contains a markdown link to our Getting Involved page: https://www.notion.so/chayn/Get-involved-423c067536f3426a88005de68f0cab19?pvs=4 

### Resources/Instructions
- [How to make Markdown Links](https://www.markdownguide.org/basic-syntax/#links)

**Comment by FardeenCODEIIEST** [comment]
Hey @kyleecodes , can you assign me this issue.

**Comment by kyleecodes** [comment]
Hey @FardeenCODEIIEST thank you for your interest! I'm keeping this issue open to others because only 1 no-code hacktober issue is allowed per person and you've already been assigned another no-code issue on this repo!

**Comment by FardeenCODEIIEST** [comment]
Ok @kyleecodes , no problem

**Comment by kyleecodes** [comment]
Closed: https://github.com/chaynHQ/bloom-backend/commit/2992f43ec00c2a88fe01d7a5129e24d9ef0f5cf4
