### ISSUE TITLE
Create new PATCH partner endpoint

### ISSUE THREAD

**Issue by eleanorreem** [chaynHQ/bloom-backend#418]
### Overview
We want to at some point be using Rest properly. Currently, this is not the case. Each endpoint which deviates from REST patterns should be duplicated and corrected. We can later migrate the frontend over to the correct endpoint and delete the incorrect usage. We don't need to be super strict but just better than where we are now. 

Our current url POST `/v1/partner/delete` does not make sense. Firstly, this is because functionally it is a soft delete. We merely set the status of the partner from active to inactive. Secondly the usage of POST is incorrect. 

### Action Items

- [ ] See /bloom-backend/src/partner/partner.controller.ts. Look for the POST `/v1/partner/delete` endpoint. We want to replicate the functionality of this endpoint. 
- [ ] We want this url to be a PATCH request with the url  `/v1/partner/:id` and with a body that accepts `{active: boolean}` .
- [ ] You will also need to create a new service method with a different name. Instead of `deletePartner`, it should be `updatePartner`.  `updatePartner` should take both the partnerId and a body DTO which all the changes inside. Please see bloom-backend/src/partner-feature/partner-feature.service.ts. Look at `updatePartnerFeature` as an example. 
- [ ] Please feel free to delete the old version. 
- [ ] Create a test file with a new test for the new service method. It would be good to cover the pass and fail scenario. 

### Resources/Instructions

- the bloom-backend/src/partner-feature/partner-feature.service.ts folder  is a better example of how we want our controllers and services to be structured. Take a look at those so you have an understanding of our preferred patterns.

**Comment by chinmaym07** [comment]
Can I give it a try ?

**Comment by eleanorreem** [comment]
@chinmaym07  sorry for the delay! I missed this notification. You have been assigned 😄

**Comment by chinmaym07** [comment]
@kyleecodes @eleanorreem  I am working on this. will create the PR by this week.

**Comment by kyleecodes** [comment]
@chinmaym07 appreciate the update! We recently updated our stale bot so it labeled this stale a few days early by accident. Please let us know if you have any questions.

**Comment by SangilYun** [comment]
@eleanorreem @kyleecodes If no one is working on this can I do this issue?
