### ISSUE TITLE
Add upto date database schema image to docs /data-architecture.md

### ISSUE THREAD

**Issue by eleanorreem** [chaynHQ/bloom-backend#423]
### Overview
We need to update our [database architectural docs](https://github.com/chaynHQ/bloom-backend/blob/develop/docs/data-architecture.md). 

### Action Items

- [ ] Create a new section called Database Schema and add the following image:

<img width="1223" alt="Screenshot 2024-05-13 at 14 52 09" src="https://github.com/chaynHQ/bloom-backend/assets/16049515/b2d4e749-e920-4775-98a3-84c9ff68bca1">

- [ ] Replace the current Database model diagram and replace with this image: 

<img width="791" alt="Screenshot 2024-05-13 at 14 53 24" src="https://github.com/chaynHQ/bloom-backend/assets/16049515/7b7e17fd-e3c0-4df7-b644-b9e3c29bd907">

**Comment by eleanorreem** [comment]
Hi @LouisVdwl, Thanks for volunteering for this ticket. You have been assigned!

**Comment by kyleecodes** [comment]
Hey @LouisVdwl, we requested one minor change on your PR. Please check the PR discussions so we can merge. :)

**Comment by LouisVdwl** [comment]
> Hey @LouisVdwl, we requested one minor change on your PR. Please check the PR discussions so we can merge. :)

Hey @kyleecodes, I updated the PR #424 :)
