### ISSUE TITLE
Delete the POST /user/me endpoint 

### ISSUE THREAD

**Issue by eleanorreem** [chaynHQ/bloom-backend#425]
### Overview
This ticket involved removing an outdated POST /user/me endpoint. This issue was blocked [by a frontend issue](https://github.com/chaynHQ/bloom-frontend/issues/906). The frontend needs to be migrated over to the new GET /user/me endpoint before this endpoint is deleted. 

### Action Items
- [ ] Remove the POST /user/me endpoint from the user.controller.ts
- [ ] Run unit tests to ensure everything is still working as expected.
- [ ] Run Cypress tests to ensure everything is still working as expected

**Comment by SangilYun** [comment]
Hi @eleanorreem! Can I work on this?

**Comment by eleanorreem** [comment]
Hi @SangilYun, Thanks for your interest 😄 Note that this issue is blocked until the linked frontend ticket is completed.I will update you when that ticket is complete! Let me know if you have any questions!

**Comment by kyleecodes** [comment]
@SangilYun, this issue is now unblocked.

**Comment by kyleecodes** [comment]
Hi @SangilYun, thank you for your contributions to Chayn! I know you have been busy with other contributions, but are you still working on this one? Take as much time as you need. I am just checking in after a month of inactivity. Let us know if there's anything you need or if you would like to be unassigned this issue. Thanks again.

**Comment by eleanorreem** [comment]
@kyleecodes this one was completed a while back and merged.
