### ISSUE TITLE
Create GET /subscription_user endpoint 

### ISSUE THREAD

**Issue by eleanorreem** [chaynHQ/bloom-backend#429]
### Overview
We want to start breaking up the GET /user/me request and only fetch information on the pages it is needed. This is starting with subscriptions. We also are misusing types across the site so we want to improve the ways of transferring data. Note that we don't want any DTOs to be used in the service, only in the controllers. We are also phasing out all ITypes such as ISubscriptionUser. All formatting needs to happen in the controller. I have labelled this ticket as advanced, not because of the complexity, but because of the confidence needed in controller/service interactions and appropriate types. 

### Action Items
- [ ] get familiar with Nestjs best practices with the resources below
- [x] Create a service method that return an array of SubscriptionEntities for a user. Please note, you will want to be returning the subscription name i.e. whatsapp, not just the subscription_user table. this might look like `SubscriptionUserService.getSubscriptions(userId)`
- [x] Create a GetSubscriptionUsersDto which returns an array of GetSubscriptionUserDto (you might want to make 2 dtos, one that returns an array of the other)
- [x] The GetSubscriptionUserDto needs to have the following properties: 
- [x] ```
      {
        id: string;
        subscriptionId: string;
        subscriptionName: string;
        subscriptionInfo: string;
        createdAt: Date;
        cancelledAt: Date | null;
      }
```
- [ ] Create a GET /subscription_user endpoint that returns all the subscriptions of the authenticated user. It should return a GetSubscriptionUsersDto. Please use NestJs recommended guidance to build the DTO rather than using the pattern that is in use on the site as it is incorrect. Formatting the return DTO needs to happen in the controller  


### Resources
- https://docs.nestjs.com/openapi/types-and-parameters
- https://docs.nestjs.com/openapi/mapped-types
- https://medium.com/ayuth/proper-way-to-create-response-dto-in-nest-js-2d58b9e42bf9

**Comment by Tim-Quattrochi** [comment]
@eleanorreem Can I please take on this issue? thanks.

**Comment by Tim-Quattrochi** [comment]
@eleanorreem  Just wanted to get some clarification. You said the the service should just return the name, and the controller should return the 'GetSubscriptionUsersDto', this is my return response right now: 
![Screenshot 2024-08-10 at 11 41 15 PM](https://github.com/user-attachments/assets/a7f54591-5bc9-43b8-9a67-5e2d317e2c92)

**Comment by Tim-Quattrochi** [comment]
Progress: Need to refactor, test more. 

<img width="1507" alt="Screenshot 2024-08-11 at 5 38 34 AM" src="https://github.com/user-attachments/assets/ed228ab4-8819-4aa5-80b0-c1f5e61a3557">

**Comment by kyleecodes** [comment]
> @eleanorreem Just wanted to get some clarification. You said the the service should just return the name, and the controller should return the 'GetSubscriptionUsersDto', this is my return response right now: ![Screenshot 2024-08-10 at 11 41 15 PM](https://private-user-images.githubusercontent.com/89536242/356848746-a7f54591-5bc9-43b8-9a67-5e2d317e2c92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2NjA2NjMsIm5iZiI6MTcyMzY2MDM2MywicGF0aCI6Ii84OTUzNjI0Mi8zNTY4NDg3NDYtYTdmNTQ1OTEtNWJjOS00M2I4LTlhNjctNWUyZDMxN2UyYzkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDE4MzI0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2YWNlNTEzZjEwZDBlYTg0NzNmMjljOTIwMjFiZTZmNTM3NTU0Mzg1Mzg5NjIyNTk1NDExNjE2ODMwMzQ3ZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eC3C-mj2vn9j4BpBEkV1uJXsmjF6_uJxwvFGwbcY3hU)

Hi @Tim-Quattrochi thank you for your contribution! Great question. Eleanor is off right now until Monday, I will ping her to come here and answer your question. Thanks for your patience!
