### ISSUE TITLE
Fix Typo in Contributing File

### ISSUE THREAD

**Issue by kyleecodes** [chaynHQ/bloom-backend#441]
### Overview
For new to open-source volunteers - the word "sustainable" in the Contributing Docs[ under the Issue Limit Policies header](https://github.com/chaynHQ/bloom-backend/blob/develop/CONTRIBUTING.md#issue-limit-policies) is misspelled and needs corrected. This issue is best for contributors new to open-source because it does not require local development. However we recommend contributors still clone the repo locally and follow all the steps in the Contributing file.

### Action Items
- [ ] Read and follow the directions in the Contributing file.
- [ ] Correct the typo: sustainble -> sustainable.
- [ ] Open a pull request.

**Comment by jasonmokk** [comment]
Hello, I'd like to work on this.

**Comment by kyleecodes** [comment]
Hey @jasonmokk This task is currently reserved for volunteers with Chayn. Please check back in 3 weeks for more issues like this to contribute. Thanks!

**Comment by GrannyYetta** [comment]
Hiya! I'd like to work on this issue :)

**Comment by GrannyYetta** [comment]
This issue should be completed, but I would appreciate any feedback.

**Comment by kyleecodes** [comment]
Hey @GrannyYetta I do not see a pull request for this issue. Sent you a message on Slack.

**Comment by GrannyYetta** [comment]
The pull request should be available now in the following link: (https://github.com/chaynHQ/bloom-backend/pull/512)
