### ISSUE TITLE
Refactor user fetching to remove unnessary joins

### ISSUE THREAD

**Issue by annarhughes** [chaynHQ/bloom-backend#454]
### Is your feature request related to a problem?
Most of our backend api requests are related to users, so before the request function is run, we get the current user from the database and make the user data available in the request and following functions. The problem is that for each request, we are calling the user data with joins to all relationships, whilst the related data is not usually required for the current request. E.g. the api request for a user starting a session, does not require the `createSessionUser` to have access to `user.partnerAccess` or `user.therapySession` relationship data, but it is still being requested.

### Describe a solution:
- Remove the joins in `getUserByFirebaseId` function in [user.service.ts](https://github.com/chaynHQ/bloom-backend/issues/src/user/user.service.ts) so that the `userEntity` request context only includes the user data with no joins/relations.
- Ensure no functions are now broken, i.e. any functions that _did_ use the relationships will no longer have access to the required data. Look for functions that use this data by searching for `req['userEntity']`. I couldnt see any uses of `user.relationships` but should be double checked.

This change will massively improve the performance of the API and the code complexity and maintainability in future!

**Comment by reidn3r** [comment]
Could someone assign this to me? Actually, I already made a pull request trying to solve this issue
