### ISSUE TITLE
Add testing clause to pull request template

### ISSUE THREAD

**Issue by kyleecodes** [chaynHQ/bloom-backend#489]
### Overview
This issue is best for contributors new to open-source because it does not require local development. However we recommend contributors still clone the repo locally and follow all the steps in the Contributing file for learning.

Task: Update the pull request template for this repo with a testing clause from the bloom-frontend repo. The pull request template can be found in the `./github/pull_request.md` file.

### Action Items
- [ ] Read the Contributing File 
- [ ] Copy the the pull request template from bloom-frontend into bloom-backend's pull request template. Note: this file is a Markdown file, so there is hidden text in the raw file. You can view the raw text in the UI by viewing the file and clicking the Raw option in the top right corner. 
- [ ] Submit a pull request.

### Resources
- [Docs: Quickstart for writing on GitHub](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/quickstart-for-writing-on-github)

**Comment by KatherineDonald** [comment]
Interested in taking this on. Can you please assign it to me?
