### ISSUE TITLE
Update message send when user account is deleted

### ISSUE THREAD

**Issue by eleanorreem** [chaynHQ/bloom-backend#519]
### Overview
We send a slack message to one of our channels when a user wants to be deleted. The current text is misleading and we want to update it. In file bloom-backend/src/therapy-session/therapy-session.service.ts It currently is:
```
  await this.slackMessageClient.sendMessageToTherapySlackChannel(
      `User has requested to be deleted - please delete user with emails ${userEmail + emails.join(', ')} from Simplybook, Crisp and from Mailchimp`,
    );

```

what it really should be is:
```
  await this.slackMessageClient.sendMessageToTherapySlackChannel(
      `User has been deleted from bloom - please remove the accounts associated with ${userEmail + emails.join(', ')} from Simplybook, Crisp and from Mailchimp`,
    );
```

### Action Items

- [ ] Make changes to the message sent
- [ ] Run tests and fix anything that has broken

**Comment by AT-TMC** [comment]
Can I be assigned this?
