### ISSUE TITLE
 Update requested issues in Contributing Guide

### ISSUE THREAD

**Issue by kyleecodes** [chaynHQ/bloom-backend#529]
### Overview
This is a no-code documentation issue, ideal for contributors new to open-source. 

### Action Items
In our Contributing Guidelines (the `CONTRIBUTING.md` file), under the "**What kind of contributions does Chayn want?**" headline, update the list of issues to:

```
- additional software tests / test coverage
- dependency updates *check Dependabot pull requests 
- code (requested features, bug fixes, quality enhancements, maintenance help)
- accessibility and language support.
- no-code (documentation, translations) *see spam policy below for accepted documentation changes.
```
Notice there is a spelling mistake in "documentation", you should fix this by copy pasting the text above.

### Resources/Instructions

- [How to Write in Markdown Guide](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax)

**Comment by KatherineDonald** [comment]
Hi @kyleecodes please assign this to me :)
