### ISSUE TITLE
Update the deletedAt Column when a user requests to be deleted

### ISSUE THREAD

**Issue by eleanorreem** [chaynHQ/bloom-backend#531]
### Overview
When a user requests to be deleted they hit the deleteUser method in the [user service](https://github.com/chaynHQ/bloom-backend/blob/develop/src/user/user.service.ts). This method soft deletes the user and sets them to inactive. We want to record the date in the new `user.deletedAt` column. The ticket is dependent on #530 

### Action Items

- [ ] Ensure the user deletedAt date is set upon deletion
- [ ] Ensure tests pass
- [ ] Tag @eleanorreem or @annarhughes

**Comment by ckirby19** [comment]
Hello, I would like to pick this up once #530 is merged :)

**Comment by eleanorreem** [comment]
@ckirby19 ready to go if you are still interested

**Comment by ckirby19** [comment]
Apologies, I will have a chance to pick this up over the weekend!

**Comment by eleanorreem** [comment]
No rush! Just flagging that this is now unblocked 😄

**Comment by ckirby19** [comment]
Hello, I was not able to test this properly locally as I wanted to, as I could not get the new database dump to work, with the error
`pg_restore: warning: archive is compressed, but this installation does not support compression (this build does not support compression with gzip) -- no data will be available
pg_restore: error: cannot restore from compressed archive (this build does not support compression with gzip)` 
Any suggestions for this?

**Comment by kyleecodes** [comment]
Hi @ckirby19, was this error thrown by pgAdmin or a command line tool? Never seen this error before. But this may be an issue with our dump file that needs updated to exclude permission tags. If you follow directions exactly as they are in the Wiki guide (linked in README) it should work regardless.

**Comment by ckirby19** [comment]
Hello, this PR was merged, is there anything else needed for this? I would have to check again about the error I saw above. I followed the readme but the error above was what I got

**Comment by eleanorreem** [comment]
My bad forgot to mark as closed!
