### ISSUE TITLE
Replace req["user"] with req["userEntity"] in session-user.controller

### ISSUE THREAD

**Issue by eleanorreem** [chaynHQ/bloom-backend#546]
### Overview
Take a read through the umbrella [ticket](https://github.com/chaynHQ/bloom-backend/issues/453). As a sub task to this ticket we want to phase out the use of `req["user"]` from the session-user.controller.ts. The endpoints that need addressing are POST /session-user, POST /session-user/complete, POST /session-user/incomplete. Note that we haven't followed rest patterns here and hopefully this will be refactored at a later date but not part of this ticket. 

### Action Items
- [ ] For each endpoint that uses `req["user"]`, the service methods will need to be refactored to take the `req["userEntity"]` rather than `req["user"]`. This means the service methods will be taking userEntity rather than `GetUserDto` as its argument. The types need to be updated in the service method and adjustments will need to be made if they are used elsewhere.  
- [ ] Run all tests. This includes Cypress tests. You will need to load the frontend repository to get instructions about how this works. https://github.com/chaynHQ/bloom-frontend

**Comment by leoseg** [comment]
Hi I would like to take up this issue, can you assign it to me? :)

**Comment by leoseg** [comment]
Hi I created the pull request :) https://github.com/chaynHQ/bloom-backend/pull/567
