### ISSUE TITLE
Update pull request template with resolves keyword

### ISSUE THREAD

**Issue by kyleecodes** [chaynHQ/bloom-backend#612]
### Overview
Our pull request templates do not link their related issues within GitHub. To do this, we must add a `resolves` keyword as described in these GitHub docs: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue. There are other options for keywords, but we are using `resolves`. 

### Action Items
- [ ] Update `/.github/pull_request_template.md` to use 'resolves' keyword. The developer should be prompted to link the issue after the resolves keyword in place of  "Issue link / number:". Additional directions (hidden or visible) may be added for clarification.

### Resources
[Markdown Cheatsheet](https://www.markdownguide.org/cheat-sheet/)

**Comment by kyleecodes** [comment]
@GrannyYetta

**Comment by GrannyYetta** [comment]
Hi, can I get this issue assigned, please?
